# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: Ablaze.Floorp
PackageVersion: 11.26.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
Commands:
- floorp
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- jxl
- pdf
- shtml
- svg
- url
- webp
- xht
- xhtml
ReleaseDate: 2025-04-29
Scope: machine
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
ElevationRequirement: elevatesSelf
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Floorp-Projects/Floorp/releases/download/v11.26.0/floorp-win64.installer.exe
  InstallerSha256: 04A852701B16F86512EC6C295D474EB0EA898E6CC2BC7D5AB438322BD9EC6AC9
  AppsAndFeaturesEntries:
  - DisplayName: Ablaze Floorp (x64 en-US)
    ProductCode: Ablaze Floorp 11.26.0 (x64 en-US)
ManifestType: installer
ManifestVersion: 1.9.0
